travis:
  secure:
    BINSTAR_TOKEN: pLgdA/YU9byMyiFhmCt+INjcUTyGvy7sI2dus4MdnxfmraWTtbBCUs0vD2uJIQ+wdkkxmDWbl7I61xLmcnyvGhMobPLpY8ROyCPALBkmtJpyCvhvIVZhyMIjKOAr1lkmAocG4+bl7sWL4IJJEXV6R3fW/FoTc2rpqMt5n+1clKR88EoVnrlxBgDOc5E+1uZq/XEh01QgcEFlEVldBVDXVxIvUaS1v4j4UNVtek6g6Fm7nm30gV5JJLClrla8Nm9Jkxack75yzKlg6B93ua6X/Iv7pqGaTIcvXYGqxkMHBHt9jZLVp7q4G7et14HLTG7BGYnnJbXxc5VMDym/U0UluvgGMDqNpxBta9h6vHg01ZQgnensggJ7Y9kmeMs0LufGqWHNVmlP+TClFm4YBfzgdgSNANaz/NQggLr5uFVoP4rl3cBVIQMAtObXBVNLE/NMm1IqWifUYDsdq0SH44L8qS32H8TaVaXskSmNE3UBd8newrRrG4lOxSaJduHZN22XAnrRj04jprRJedVYcQJ0SdSQL1euE6w3RUCxCZf93Bn5zmSZ1izdas+8VIRadrzDmyBOPM8+d7b75bdX//1fvTqqcs6I0TapmqBBl1ZvAd5nA+/jYteyDkXAXFFaWoDFlvp/1CwRzfnZ7FRe837qLnoZ6NTeH+emFvSxOd5pF8g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
